#!/usr/bin/env python3
#
# csvxfgexp
#
# Made by Rogier Visser (Laansloot IT)
# 17 March 2020

import csv, uuid, sys
from lxml import etree
from lxml.etree import fromstring


#
# Step 1. Set variables
#

searchvalue = sys.argv[1]
translations = "ssd_form_translations.csv"
forms = "ssd_form.csv"


#
# Step 2. Set functions
#

def converttounid(unid):
	i = uuid.UUID(unid)
	b = i.bytes
	return uuid.UUID(bytes=b)

def getrecord(searchvalue):
	with open(translations, mode='r', encoding='utf-8-sig') as csv_file:
		csv_reader = csv.DictReader(csv_file, delimiter=';', quotechar='"')
		results = []
		for row in csv_reader:
			if row["title"] == searchvalue:
				transunid = row["unid"]
				formunid = row["formid"]
				prefixunid = str(converttounid(formunid))[0:8]
				translation = row["translation"]
				results.append(prefixunid)
		if len(results) == 1:
			return (prefixunid, transunid, formunid, translation)
		elif len(results) > 1:
			print("Multiple form titles found. ERROR")
		else:
			print("Form title not found. ERROR")
			
def getform(formunid):
	with open(forms, mode='r', encoding='utf-8-sig') as csv_file:
		csv_forms = csv.DictReader(csv_file, delimiter=';', quotechar='"')
		for row in csv_forms:
			if row["unid"] == formunid:
				return (row["form"], row["card"])
				
def createxml(xmlin, filename):
	with open(filename, 'w') as file2:
		parser = etree.XMLParser(encoding='utf-8', remove_blank_text=True)
		xmlout = fromstring(xmlin, parser=parser)
		print(etree.tostring(xmlout, pretty_print=True, xml_declaration=True, encoding='utf-8', standalone=True).decode(), file=file2)


#
# Step 3. Get the data!
#

uniqueform = getrecord(searchvalue)
if uniqueform:
	print("Form title search \"" + searchvalue + "\"")
	print("---------------------------------------")

	translationfilename = uniqueform[0] + "-translation.txt"
	with open(translationfilename, 'w') as file1:
		print(uniqueform[3], file=file1)
		print("Exporting " + translationfilename)

	xmlformfilename = uniqueform[0] + "-form.xml"
	createxml(getform(uniqueform[2])[0].encode('utf-8'), xmlformfilename)
	print("Exporting " + xmlformfilename)

	xmlcardfilename = uniqueform[0] + "-card.xml"
	createxml(getform(uniqueform[2])[1].encode('utf-8'), xmlcardfilename)
	print("Exporting " + xmlcardfilename)

	unidfilename = uniqueform[0] + "-unids.txt"
	with open(unidfilename, 'w') as file3:
		print("unidtrans:" + str(converttounid(uniqueform[1])), file=file3)
		print("unidform:" + str(converttounid(uniqueform[2])), file=file3)
		print("title:" + searchvalue, file=file3)
		print("Exporting " + unidfilename)

	print("---------------------------------------")
