#!/usr/bin/env python3
#
# csvxfgimp
#
# Made by Rogier Visser (Laansloot IT)
# 17 March 2020

import csv, sys


#
# Step 1. Write the data
#

prefixunid = sys.argv[1]

unidfilename = prefixunid + "-unids.txt"
unids = []
with open(unidfilename, "r") as file1:
	for line in file1.readlines():
		keys = line.strip().split(":")
		unids.append(keys[1])
unidtrans = unids[0]
unidform = unids[1]
title = unids[2]

print("Found form \"" + title + "\"")
print("---------------------------------------")

translationfilename = prefixunid + "-translation.txt"
with open(translationfilename, "r") as file2:
	print("Importing " + translationfilename)
	translation = file2.read().strip()

xmlformfilename = prefixunid + "-form.xml"
with open(xmlformfilename, "r") as file3:
	form = "".join(line.strip() for line in file3)
	print("Importing " + xmlformfilename)

xmlcardfilename = prefixunid + "-card.xml"
with open(xmlcardfilename, "r") as file4:
	card = "".join(line.strip() for line in file4)
	print("Importing " + xmlcardfilename)

exportcsv = "XFG-import.csv"
with open(exportcsv, 'w', newline='') as file5:
	file1.write("unidform;form;card;unidtrans;translation\n")
	writer = csv.writer(file5, delimiter=';', quoting=csv.QUOTE_ALL)
	writer.writerow([unidform, form, card, unidtrans, translation])

print("---------------------------------------")
print("Exporting " + exportcsv)
